
spring:

  datasource:                #msyql数据库
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: qiuhen

#jpa
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

#日志
logging:
  level:
    root: warn
    com.qiuhen: info
  file:
    name: blog-pro.log
    path: log/
