
spring:

  datasource:                #msyql数据库
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: qiuhen

#jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
#日志
logging:
  level:
    root: info
    com.qiuhen: info


  file:
    name: blog-dev.log
    path: log/
